.include"m32def.inc"
 LDI R16,0XFF
 OUT DDRD,R16
REPEAT: SBI PORTD,0
 		CALL DELAY
 		SBI PORTD,1
 		CALL DELAY
 		SBI PORTD,2
 		CALL DELAY 
		SBI PORTD,3
 		CALL DELAY
		SBI PORTD,4
		CALL DELAY
 		SBI PORTD,5
 		CALL DELAY
 		SBI PORTD,6
 		CALL DELAY
 		SBI PORTD,7
 		CALL DELAY
 		CBI PORTD,7
 		CALL DELAY
 		CBI PORTD,6
 		CALL DELAY
 		CBI PORTD,5
 		CALL DELAY
 		CBI PORTD,4
 		CALL DELAY
 		CBI PORTD,3
 		CALL DELAY
 		CBI PORTD,2
 		CALL DELAY
 		CBI PORTD,1
 		CALL DELAY
 		CBI PORTD,0 
		CALL DELAY
 		JMP REPEAT
DELAY: 	   LDI R18,0XFF
	LOOP2: LDI R17,0XFF
	LOOP1: DEC R17
 		   BRNE LOOP1
 		   DEC R18
 		   BRNE LOOP2
 		   RET
	
